<!DOCTYPE html>
<html>
<title>多维度运营数据</title>
<head>
    <link rel="stylesheet" type="text/css" href="/public/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="/public/js/My97DatePicker/skin/WdatePicker.css">
    <script type="text/javascript" language="javascript" src="/public/js/jquery.js"></script>
    <script type="text/javascript" language="javascript" src="/public/js/My97DatePicker/WdatePicker.js"></script>
    <script type="text/javascript" language="javascript" src="/public/js/jquery.dataTables.js"></script>
    <script type="text/javascript" language="javascript" src="/public/js/main.js"></script>



    <style>
        div.container {
            margin: 0 auto;
            max-width:760px;
        }
        div.header {
            margin: 100px auto;
            line-height:30px;
            max-width:760px;
        }
        body {
            background: #f7f7f7;
            color: #333;
            font: 90%/1.45em "Helvetica Neue",HelveticaNeue,Verdana,Arial,Helvetica,sans-serif;
        }
    </style>
</head>
<body>
<div class="header"><h1>基于城市的周下线活动详情</h1></div>
<div class="container" >
    <select id="dataType" data-rel="chosen" >
        <option value="0">请选择</option>
        <option value="1">基于城市的周订单量</option>
        <option value="2">基于城市的周上下线活动数量</option>
        <option value="3">投诉类型统计</option>
        <option value="4">运营标签点击次数</option>
        <option value="5">睡前摇(验证率)</option>
        <option value="6">往下拍(验证率)</option>
        <option value="7">往下拍(销售率)</option>
        <option value="8">标签(对应销售)</option>
        <option value="9">下线原因明细</option>
        <option value="10">活动销售率</option>
    </select>

    <input id="startDate" class="Wdate" type="text" value=<?php echo $startDate?> onFocus="WdatePicker({maxDate:'#F{$dp.$D(\'endDate\')||\'2020-10-01\'}'})"/>
    <input id="endDate" class="Wdate" type="text" value=<?php echo $endDate?> onFocus="WdatePicker({minDate:'#F{$dp.$D(\'startDate\')}',maxDate:'2020-10-01'})"/>
    <button type="button" onclick=find()>查询</button>
    <button type="button" onclick=excelExport()>excel导出</button>
    <table id="weekDataTable"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
        <thead>
        <tr>
            <th>投诉类型</th>
            <th>数量</th>
        </tr>
        </thead>
    </table>
</div>
</body>
</html>
